version: '3.9'
services:
  web:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
      - ${APP_PORT}:81 
    networks:
      - default
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
