version: '3.9'
services:
  web:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - 8180:80
      - 8181:81
      - 8143:443
    networks:
      - default
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
